# -*- mode: org; fill-column: 78; -*-
# Time-stamp: <2024-10-02 18:38:53 krylon>
#
#+TAGS: internals(i) ui(u) bug(b) feature(f)
#+TAGS: database(d) design(e), meditation(m)
#+TAGS: optimize(o) refactor(r) cleanup(c)
#+TODO: TODO(t)  RESEARCH(r) IMPLEMENT(i) TEST(e) | DONE(d) FAILED(f) CANCELLED(c)
#+TODO: MEDITATE(m) PLANNING(p) | SUSPENDED(s)
#+PRIORITIES: A G D

* BadNews
  BadNews is an RSS reader
** Clock table
   #+BEGIN: clocktable :scope file :maxlevel 202 :emphasize t
   #+CAPTION: Clock summary at [2024-10-02 Mi 18:38]
   | Headline                            | Time      |           |       |      |      |
   |-------------------------------------+-----------+-----------+-------+------+------|
   | *Total time*                        | *1d 3:48* |           |       |      |      |
   |-------------------------------------+-----------+-----------+-------+------+------|
   | *BadNews*                           | *1d 3:48* |           |       |      |      |
   | \_  /Components [0/0]/              |           | /1d 3:48/ |       |      |      |
   | \_    Data model [0/0]              |           |           |  0:27 |      |      |
   | \_    Database [1/1]                |           |           |  8:30 |      |      |
   | \_      Queries respect transaction |           |           |       | 0:03 |      |
   | \_    Feed catcher / parser [0/0]   |           |           |  5:41 |      |      |
   | \_      Testing                     |           |           |       | 2:16 |      |
   | \_    Web Interface [0/0]           |           |           | 13:10 |      |      |
   | \_      Appearances matter [3/3]    |           |           |       | 3:43 |      |
   | \_        Images                    |           |           |       |      | 0:12 |
   | \_        Hide long descriptions    |           |           |       |      | 0:20 |
   | \_        Fix Links                 |           |           |       |      | 0:03 |
   | \_      AJAX FTW [0/0]              |           |           |       | 3:02 |      |
   #+END:
** Journal
** Features [0/0]
   :PROPERTIES:
   :COOKIE_DATA: todo recursive
   :VISIBILITY: children
   :END:
** Components [0/0]
   :PROPERTIES:
   :COOKIE_DATA: todo recursive
   :VISIBILITY: children
   :END:
*** Data model [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: children
    :END:
    :LOGBOOK:
    CLOCK: [2024-09-19 Do 16:25]--[2024-09-19 Do 16:52] =>  0:27
    :END:
*** Database [1/1]                                                 :database:
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: children
    :END:
    :LOGBOOK:
    CLOCK: [2024-10-01 Di 18:27]--[2024-10-01 Di 18:35] =>  0:08
    CLOCK: [2024-09-24 Di 14:42]--[2024-09-24 Di 14:44] =>  0:02
    CLOCK: [2024-09-23 Mo 20:45]--[2024-09-23 Mo 21:37] =>  0:52
    CLOCK: [2024-09-21 Sa 20:35]--[2024-09-21 Sa 20:42] =>  0:07
    CLOCK: [2024-09-21 Sa 15:52]--[2024-09-21 Sa 16:00] =>  0:08
    CLOCK: [2024-09-21 Sa 13:52]--[2024-09-21 Sa 15:41] =>  1:49
    CLOCK: [2024-09-20 Fr 21:10]--[2024-09-20 Fr 21:46] =>  0:36
    CLOCK: [2024-09-20 Fr 10:19]--[2024-09-20 Fr 10:55] =>  0:36
    CLOCK: [2024-09-19 Do 16:52]--[2024-09-19 Do 21:01] =>  4:09
    :END:
**** DONE [#A] Queries respect transaction                              :bug:
     CLOSED: [2024-09-24 Di 19:08]
     :LOGBOOK:
     CLOCK: [2024-09-24 Di 19:05]--[2024-09-24 Di 19:08] =>  0:03
     :END:
     All database methods that query the database but do not change it, need
     to check if the database has an ongoing transaction and if so, need to
     use =stmt = db.tx.Stmt(stmt)=.
     [2024-09-24 Di 19:06] Turns out, I /already/ do that. Which is both a bit
     embarassing (insofar I did not remember) and a relief (insofar I
     obviously did think of this before).
*** Feed catcher / parser [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: children
    :END:
    :LOGBOOK:
    CLOCK: [2024-09-24 Di 19:08]--[2024-09-24 Di 20:06] =>  0:58
    CLOCK: [2024-09-24 Di 17:18]--[2024-09-24 Di 19:05] =>  1:47
    CLOCK: [2024-09-24 Di 14:45]--[2024-09-24 Di 15:25] =>  0:40
    :END:
**** Testing
     :LOGBOOK:
     CLOCK: [2024-09-26 Do 17:56]--[2024-09-26 Do 20:12] =>  2:16
     :END:
*** Web Interface [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: children
    :END:
    :LOGBOOK:
    CLOCK: [2024-09-30 Mo 18:27]--[2024-09-30 Mo 23:50] =>  5:23
    CLOCK: [2024-09-30 Mo 17:50]--[2024-09-30 Mo 18:21] =>  0:31
    CLOCK: [2024-09-30 Mo 13:35]--[2024-09-30 Mo 13:46] =>  0:11
    CLOCK: [2024-09-29 So 16:10]--[2024-09-29 So 16:30] =>  0:20
    :END:
    For an RSS reader, a web interface is the obvious approach, isn't it?
**** Appearances matter [3/3]
     :PROPERTIES:
     :COOKIE_DATA: todo recursive
     :VISIBILITY: children
     :END:
     :LOGBOOK:
     CLOCK: [2024-10-01 Di 19:39]--[2024-10-01 Di 22:47] =>  3:08
     :END:
***** DONE Images
      CLOSED: [2024-10-02 Mi 18:14]
      :LOGBOOK:
      CLOCK: [2024-10-02 Mi 18:02]--[2024-10-02 Mi 18:14] =>  0:12
      :END:
      This is something I tackled but didn't get right with the old app, I
      /want/ to have images referenced in the RSS descriptions displayed, but
      I want them to be modestly sized.
***** DONE Hide long descriptions
      CLOSED: [2024-10-02 Mi 18:35]
      :LOGBOOK:
      CLOCK: [2024-10-02 Mi 18:15]--[2024-10-02 Mi 18:35] =>  0:20
      :END:
      In the old ticker app, I would hide lengthy article descriptions behind
      a button that would reveal the entire text + images. I should just copy
      that verbatim.
***** DONE Fix Links
      CLOSED: [2024-10-02 Mi 18:38]
      :LOGBOOK:
      CLOCK: [2024-10-02 Mi 18:35]--[2024-10-02 Mi 18:38] =>  0:03
      :END:
      I want to make sure any links within item descriptions are opened in new
      tabs or windows.
**** AJAX FTW [0/0]
     :PROPERTIES:
     :COOKIE_DATA: todo recursive
     :VISIBILITY: children
     :END:
     :LOGBOOK:
     CLOCK: [2024-10-01 Di 18:55]--[2024-10-01 Di 19:29] =>  0:34
     CLOCK: [2024-10-01 Di 18:35]--[2024-10-01 Di 18:51] =>  0:16
     CLOCK: [2024-10-01 Di 17:25]--[2024-10-01 Di 18:27] =>  1:02
     CLOCK: [2024-10-01 Di 14:15]--[2024-10-01 Di 15:25] =>  1:10
     :END:
     In my current news reader, loading the items views takes about forever,
     and one main goal of the rewrite is to make it at least feel more
     responsive. So I am going to try and load as much of the content as
     possible via Ajax.
** Bugs [0/0]
   :PROPERTIES:
   :COOKIE_DATA: todo recursive
   :VISIBILITY: children
   :END:


